### ISSUE TITLE
Please add getters methods for patient and study objects

### ISSUE THREAD

**Issue by DrRajJena** [scikit-rt/scikit-rt#10]
At present data that is not linked through study UID (perhaps through anonymisation or re-processing in another application) appears in distinct study objects in a single patient object.

Please could getters for patient and study objects be added, in order to retrieve a single dose cube regardless of the study object within which it is contained?

Thanks

**Comment by DrRajJena** [comment]
Thanks.

**Comment by kh296** [comment]
Getter methods are implemented as of scikit-rt 0.4.6:

- Patient:
  - [Patient.get_studies()](https://scikit-rt.github.io/scikit-rt/skrt.patient.html#skrt.patient.Patient.get_studies)
  - [Patient.get_images()](https://scikit-rt.github.io/scikit-rt/skrt.patient.html#skrt.patient.Patient.get_images)
  - [Patient.get_structure_sets()](https://scikit-rt.github.io/scikit-rt/skrt.patient.html#skrt.patient.Patient.get_structure_sets)
  - [Patient.get_doses()](https://scikit-rt.github.io/scikit-rt/skrt.patient.html#skrt.patient.Patient.get_doses)
  - [Patient.get_plans()](https://scikit-rt.github.io/scikit-rt/skrt.patient.html#skrt.patient.Patient.get_plans)
- Study:
  - [Study.get_images()](https://scikit-rt.github.io/scikit-rt/skrt.patient.html#skrt.patient.Study.get_images)
  - [Study.get_structure_sets()](https://scikit-rt.github.io/scikit-rt/skrt.patient.html#skrt.patient.Study.get_structure_sets)
  - [Study.get_doses()](https://scikit-rt.github.io/scikit-rt/skrt.patient.html#skrt.patient.Study.get_doses)
  - [Study.get_plans()](https://scikit-rt.github.io/scikit-rt/skrt.patient.html#skrt.patient.Study.get_plans)

Issue closed.
