### ISSUE TITLE
Clone header information from external RTSTRUCT file when exporting structure sets to DICOM

### ISSUE THREAD

**Issue by DrRajJena** [scikit-rt/scikit-rt#11]
Referential integrity is not always maintained when structure sets are written out by SKRT. 
Please consider an option where the relevant header information can be cloned from a source structure set file at export.

**Comment by kh296** [comment]
In principle a source file for header information can be specified already, via the `header_source` parameter of the `write()` method.  Could you give details of the problem(s) that you've encountered?

**Comment by DrRajJena** [comment]
Issue closed. Thanks.
