### ISSUE TITLE
Volume difference metric

### ISSUE THREAD

**Issue by drw25** [scikit-rt/scikit-rt#4]
I think `/ own volume` should be removed from this line of ROI.get_volume_diff() so that it returns absolute volumes.
https://github.com/scikit-rt/scikit-rt/blob/689f0dbfb8446c1eb19e53742d7c5b955c61a739/src/skrt/structures.py#L2337 Returning absolute volume seems consistent with the code of get_relative_volume_diff() and the definition of volume_diff in get_comparison(). Please can you take a look?

Thanks for your work on scikit-rt. It's great to have a Python package that handles the DICOM parsing and geometry transformation necessary to work with RT data with such simple syntax.

**Comment by kh296** [comment]
Thanks for spotting this, and apologies for the slow response.

Correction made in: [skrt.structures.ROI.get_volume_diff()](https://github.com/scikit-rt/scikit-rt/blob/9a78f29c3e7f62bf689fe41ffd173d0c1e9a6678/src/skrt/structures.py#L2420).

Test added at: [test_structs.test_get_volume_diff()](https://github.com/scikit-rt/scikit-rt/blob/9a78f29c3e7f62bf689fe41ffd173d0c1e9a6678/tests/test_structs.py#L1170).

Issue closed.
