### ISSUE TITLE
Construct Image from list of filenames

### ISSUE THREAD

**Issue by drw25** [scikit-rt/scikit-rt#5]
It would be useful to be able to construct an Image object from a list of filenames of DICOM objects (e.g. CT slices) in addition to the current option of a directory path. Alternatively a wildcard format like "/path/to/data/PAT01/CT*.dcm" might be similarly/even more useful.

I work with a clinical application that exports all DICOM objects associated with a patient into a single directory. The feature above would mean I can import the data in-place, rather than having to move all the CT slices in a series to a separate temporary directory.

**Comment by kh296** [comment]
Thanks, I think that this is a useful addition.  As of version 0.3.22, all of the following should work:

```
# Load image from a list of DICOM files.
im = Image(["/path/to/data/PAT01/CT001.dcm", "/path/to/data/PAT01/CT002.dcm"]

# Load image based on a path with wildcards.
im = Image("/path/to/data/PAT01/CT*.dcm")

# Load image by specifying a single file - other files in the directory will be found automatically.
im = Image("/path/to/data/PAT01/CT001.dcm")
```

In addition, it's possible to load multiple image series in a patient directory, or directory tree, using:
```
# Load all dicom files in, or below, the directory specified.
# Data are grouped into studies, and within each study are grouped by modality.
# Data are linked based on GUIDs.  For example, each StructureSet object knows
# the Image object with which it's associated (if data for both are present in the directory tree).
p = Patient("/path/to/data/PAT01", unsorted_dicom=True)
```
I've updated the documentation for [skrt.image.Image.__init__()](https://scikit-rt.github.io/scikit-rt/skrt.image.html#skrt.image.Image.__init__) .

Let me know if any/all of the above work for you, or if you find problems.

**Comment by kh296** [comment]
In case of problems with the new functionality, please submit new issue.

Issue closed.

**Comment by drw25** [comment]
Just tried using a list of filenames in 0.3.25 - it works great. Thanks!
