### ISSUE TITLE
Jaccard index with contour representation

### ISSUE THREAD

**Issue by drw25** [scikit-rt/scikit-rt#6]
I'm getting very different results for the Jaccard index when switching between `method="mask"` and `method="contour"` on ROIs which have multiple polygons on some slices.

I think the issue is with the `method="contour"` calculation, and some polygons are getting double counted when accumulating the union here:
https://github.com/scikit-rt/scikit-rt/blob/689f0dbfb8446c1eb19e53742d7c5b955c61a739/src/skrt/structures.py#L2473-L2483

The following code seems to produce correct results in my case:
```python
for p in positions:
    polygons1 = self.get_polygons_on_slice(view, pos=p)
    polygons2 = other.get_polygons_on_slice(view, pos=p)
    p1_slice = ops.unary_union(polygons1)
    p2_slice = ops.unary_union(polygons2)
    intersection += p1_slice.intersection(p2_slice).area * factor
    union += p1_slice.union(p2_slice).area * factor
```

**Comment by kh296** [comment]
Thanks, I agree with your correction!

Correction made in: [skrt.structures.get_intersection_union_size](https://github.com/scikit-rt/scikit-rt/blob/9a78f29c3e7f62bf689fe41ffd173d0c1e9a6678/src/skrt/structures.py#L2456).

Test added at: [test_roi_metrics.test_intersection_union_size_split_roi()](https://github.com/scikit-rt/scikit-rt/blob/9a78f29c3e7f62bf689fe41ffd173d0c1e9a6678/tests/test_roi_metrics.py#L331).

Issue closed.
