### ISSUE TITLE
Distance metrics fail for very small ROIs

### ISSUE THREAD

**Issue by drw25** [scikit-rt/scikit-rt#7]
I've been using `StructureSet.get_comparison()` to compare two structure sets which include very small ROIs (cochleas in Head & Neck datasets). scikit-rt has been throwing an exception when calculating distance metrics:
```
File /usr/local/python38-venv/lib64/python3.8/site-packages/skrt/structures.py:3326, in ROI.get_comparison(self, roi, metrics, vol_units, area_units, centroid_units, view, sl, pos, idx, method, units_in_header, global_vs_slice_header, name_as_index, nice_columns, decimal_places, force, voxel_size)
   3324         comp[m] = distances[1]
   3325     elif m == "hausdorff_distance":
-> 3326         comp[m] = distances[2]
   3327 elif m in ["mean_surface_distance_flat",
   3328         "rms_surface_distance_flat", "hausdorff_distance_flat"]:
   3329     distances_flat = (distances_flat
   3330             or roi0.get_surface_distance_metrics(roi,
   3331             view=view, flatten=True))

TypeError: 'NoneType' object is not subscriptable
```

After going through `ROI.get_comparison()`, it looks like the `ROI.match_mask_voxel_size()` method is behaving in an unexpected way for very small (possibly only single voxel) ROIs. Hopefully this summarizes the issue:

```python
#ss_ref is a StructureSet associated with a CT with voxel size (1.17,1.17,2.00) mm
#ss_test is a second StructureSet associated with the same CT as ss_ref

roi_ref =  ss_ref.get_roi("cochlear")
roi_test = ss_test.get_roi("cochlear")

# Before resampling; count number of labelled voxels in ROI masks on CT grid
roi_ref.get_mask().sum()  # returns 9
roi_test.get_mask().sum() # returns 1 (i.e. a single voxel is labelled in the mask)

# Use the method called by ROI.get_comparison() to resample the voxels to the default 1mm size
voxel_size = (1,1,1)
roi_ref_rs, roi_test_rs = roi_ref.match_mask_voxel_size(roi_test,voxel_size=voxel_size,voxel_dim_tolerance=-1)

# After resampling to the 1mm grid, count number of labelled voxels in masks
roi_ref_rs.get_mask().sum()  # returns 17 (more, as expected since the new grid is finer)
roi_test_rs.get_mask().sum()  # returns 0 (unexpected)

# This returns nothing, due to the empty mask; ROI.get_comparison() tries to index it and throws an error
roi_ref_rs.get_surface_distances(roi_test_rs)
```

I've found a workaround to calculate the distance metrics by setting the voxel size to None i.e. `StructureSet.get_comparison(...,voxel_size=None)` so that the mask is generated on the grid of the CT (although it seems quite a bit slower). I'm guessing some sort of edge case that is causing the `ROI.match_mask_voxel_size()` to fail but haven't had time to look into it. If nothing else, perhaps `StructureSet.get_comparison()` could fail in a more graceful way if the mask is empty e.g. returning NaN or None for the distance metrics?

**Comment by kh296** [comment]
Thanks, that's a very clear summary of the issue!

In your code, after the line:

```
roi_ref_rs, roi_test_rs = roi_ref.match_mask_voxel_size(roi_test,voxel_size=voxel_size,voxel_dim_tolerance=-1)
```

could you check the (`x`, `y`, `z`) extents of `roi_test_rs`, and its associated (dummy) image:

```
print("ROI extents:", roi_test_rs.get_extents())
print("Image extents": roi_test_rs.image.get_extents()) 
```

If the ROI is contained within the image, could you see if you get a non-zero sum with:

```
roi_test_rs.create_mask(force=True, overlap_level=0.25)
roi_test_rs.get_mask().sum()
```

Setting a value for overlap_level different from None results in a different algorithm being used for the mask creation.  This should label a voxel as being contained in the ROI if the fraction of the voxel volume overlapping the ROI volume is greater than overlap_level.

**Comment by kh296** [comment]
If the z resampling here is from 2 mm to 1 mm, then the ROI z extents look fine.  The values reported are the lower and upper coordinates of the image slices containing the ROI contour(s).  For an ROI with contours at 2 or more z coordinates, the slice thickness is taken to be the minimum z separation between contours at different z coordinates, so is unaffected by resampling.  For an ROI defined by a single contour, the slice thickness is taken to be the voxel z dimension of the associated image.  Maybe there needs to be a way for specifying effective thickness for single contours independently of image voxel sizes?

Could you post the pre-resampling results for:

```
print(roi_test_rs.get_contours())
print(roi_test_rs.image.get_affine())
```

That should give me enough to reproduce the problem.

**Comment by kh296** [comment]
The problem seems to be that when the ROI volume is smaller the volume of the mask voxels the ROI can be entirely contained in a single voxel or may have small overlaps with multiple voxels.  Depending on the amounts of overlap, the function ([skimage.draw.polygon2mask](https://scikit-image.org/docs/stable/api/skimage.draw.html#skimage.draw.polygon2mask)) used to label voxels as being inside the ROI can sometimes conclude that there are no voxels inside the ROI.  I've adjusted the code so that if this happens the voxel containing the ROI centroid should be labelled as being inside the ROI.  The revised code is in scikit-rt 0.3.26.  Could you update, and see if this gives any improvement with the code included in the initial issue submission?

I've also changed the handling of single-slice ROIs, so that the slice thickness used isn't changed by resampling.

**Comment by drw25** [comment]
That seems to have fixed the issue - I've updated, and no longer get errors on the problem datasets if I omit 'voxel_size=None'. Thanks!
